
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/providers";
import Footer from "@/features/app/components/Footer";


export const metadata: Metadata = {
  title: "Ummah community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
  <body>
    <Providers>
      <div className="flex min-h-screen flex-col">
        {/* Main content grows and pushes footer down */}
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </div>
    </Providers>
  </body>
</html>

  );
}
